# .linting/configs/ruff.toml  — rules-106 v1.1 compatible
# NOTE: this file is **stand-alone**, so it must start with [ruff]

[ruff]                  # what used to be [tool.ruff]
line-length = 120
target-version = "py311"

[lint]                  # what used to be [tool.ruff.lint]
select = ["E", "F", "I", "UP", "NPY"]
ignore = ["E501"]       # long lines already handled by black

[lint.isort]            # replaces the old top-level "isort" section
known-first-party = ["linguistics_agent"]
profile = "black"

[lint.pydocstyle]
convention = "pep257"

[lint.per-file-ignores]
"tests/*" = ["D", "S101"]   # skip docstring + assert-usage warnings in tests
